[package]
name = "kadev886/rozod"
version = "1.0.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[configuration]
entry_point = "src/init.luau"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"